### PR TITLE
Allow CubeViz slider to be responsive to glue slider

### LINKED ISSUE #230: Slider in Plot Options 2D Image box does not Update the Slice No./Wavelength in CubeViz
When I hit "Show Viewer Options" to open the Plot Layers 2D Image control panel, and play with
the Slider at the very bottom, which runs through image slices/wavelengths -- the wavelengths are
correctly displayed, but the corresponding slice number/wavelength in CubeViz does not update. @kassin @drdavella

### PR DESCRIPTION
**Pull request by drdavella**
This fixes #230. It will need to be reconciled with #254.

### CODE REVIEW

**Comment by drdavella** [comment]
This is ready for review and merge. It does not have the same performance as the main cubeviz slider, but a separate issue has been opened for that in #272.

**Comment by drdavella** [comment]
Test failures are due to https://github.com/glue-viz/glue/issues/1565. The bug has been fixed, but these tests won't pass until the fix is available through the `glueviz/label/dev` conda channel.

**Comment by kassin** [comment]
@astrofrog Can you put this fix in?  This is important so that the testers have something to test this week.  Thank you.

**Comment by drdavella** [comment]
@kassin the fix is already in `glue`, but it's just a matter of when it becomes available through `conda`. Typically things are built every night, so we should be able re-run the tests first thing tomorrow morning.

**Pull request merged**
