### PR TITLE
Update astropy helpers submodule

### PR DESCRIPTION
**Pull request by drdavella**
~I expect this to fail for the time being.~

### CODE REVIEW

**Comment by nmearl** [comment]
You ought to be able to just `cd` into the submodule and do a `git checkout d23a53f` (`d23a53f` being the latest pinned commit version), and then commit and push. Is it giving you issues?

**Comment by drdavella** [comment]
@nmearl that's exactly what I did to create this PR.

**Comment by drdavella** [comment]
However it was causing weird failures in another environment, so I was seeing if they would be picked up on CI. I actually think I might understand the issue now, and I think everything will be okay.

**Comment by nmearl** [comment]
> and I think everything will be okay.

Ahh, the ideal. 😁

**Comment by drdavella** [comment]
@nearl since you've already taken a quick look, do you mind approving this PR?

**Pull request merged**
