### PR TITLE
Restore single image viewer functionality

### PR DESCRIPTION
**Pull request by drdavella**
PR #130 is being broken up into two separate PRs. This new PR contains only the single image viewer functionality, along with some more general layout improvements. This is also the portion of the original PR that contains the changes introduced in #125.

This partially addresses issue #116.

### CODE REVIEW

**Comment by kassin** [comment]
Apologies if we've been through this before (I forget), but would it be possible to allow the user to resize the viewers in the single image viewer in the vertical direction and even allow the image and spectrum viewers to overlap?

**Comment by brechmos-stsci** [comment]
@kassin I don't remember a discussion about that. 

I think to resize the viewers the best is to just resize the whole window.  I suspect the way it is implemented it is not possible to resize one viewer (image or spec) in the single viewer. 

What would be the use case for this?

**Comment by kassin** [comment]
In playing around with CubeViz I kept wanting to resize either the image or the spectrum viewer to encompass my full screen (and I was working with a large screen).  If users can resize windows and allow them to overlap, they can create custom "dashboards" to suit their particular workflow.  That said, I imagine this is not something that is easily done?  @astrofrog do you have thoughts on this?

**Comment by brechmos-stsci** [comment]
@kassin Maybe best to create a new issue for this and maybe tag it with the "feature-request" label and we can discuss there.

**Comment by kassin** [comment]
window resizing is now #157

**Pull request merged**
