### PR TITLE
Allow passing in operation stack from specviz

### PR DESCRIPTION
**Pull request by nmearl**
"Apply to Cube" dialog now allows the user to select from a history of operations.

### CODE REVIEW

**Comment by nmearl** [comment]
screen shot 2018-02-14 at 2 37 10 pm

**Comment by brechmos-stsci** [comment]
Oh, cool.  This is great.

@nmearl  Could you fix the conflicts and then I'll test and merge.

**Comment by nmearl** [comment]
Oops, didn't realize this hadn't been merged. At the request of @kassin I've moved some docs around to ensure they build appropriately. This should be low key enough to attach to this PR.

**Comment by brechmos-stsci** [comment]
Tested similar to the test @nmearl did above.  Worked.  

Opened a PR to fix up the naming of the component in cubeviz passed back from specviz. https://github.com/spacetelescope/cubeviz/issues/235

**Pull request merged**
