### PR TITLE
Ifu hotfix

### PR DESCRIPTION
**Pull request by javerbukh**
* Changed PR to be merged into branch: v0.2.x

Much larger field of CTYPES to choose from, making it less likely that we will need to insert defaults. Current problem is that even if the correct CTYPES are found in hdu 0 and 1, the code will continue to go through the rest of the hdu's, see the correct CTYPES are not there, and insert the default ones. This leads to a file with 'WAVE-LOG' in hdu 1 and 'WAVE' in all the rest.

Fixes https://github.com/spacetelescope/cubeviz/issues/431

### CODE REVIEW

**Comment by brechmos-stsci** [comment]
@javerbukh You know what, I told you wrong. Make changes on master and I'll merge into 0.2.x etc.

**Comment by brechmos-stsci** [comment]
It is now coded to check for any valid combination of
```
SPECTRAL_COORD_TYPE_CODES = ["WAVE", "FREQ", "ENER", "WAVN", "VRAD", "VOPT", "ZOPT", "AWAV", "VELO", "BETA"]
NON_LINEAR_ALGORITHM_CODES = ["F2W", "F2V", "F2A", "W2F", "W2V", "W2A", "V2F", "V2W", "V2A", "A2F", "A2W", "A2V", \
                              "LOG", "GRI", "GRA", "TAB"]
```
and if found, it will accept it as correct.

**Comment by brechmos-stsci** [comment]
Using this new code the Manga data looks like:
image

Given @drlaw1558's previous comments I suspect this is correct.  The highest wavelengths goes past 10,000 A and if I understand the Halpha line it is near the 6563 but it appears there is a small redshift.

I sent an email to @drlaw1558 to confirm this looks correct.  (@drlaw1558 you can answer on here or in email).

**Comment by drlaw1558** [comment]
Indeed, wavelength solution in this plot looks correct.

**Comment by brechmos-stsci** [comment]
Nice job @javerbukh

**Pull request merged**
