### PR TITLE
Add meaningful unit tests

### LINKED ISSUE #50: Set up regression testing and CI for existing functionality

### LINKED ISSUE #53: Change pytest version comparison operator
astroconda/astroconda-dev#69 should be fixed upstream here. c/c @jhunkeler

### LINKED ISSUE #162: glueviz should not be a requirement
Remove `glueviz` from `setup.py` `install_requirements`.

`setup.cfg:install_requires = numpy>=1.13 astropy asdf pytest==3.1 glue-core>=0.12 glueviz asteval`

### PR DESCRIPTION
**Pull request by drdavella**
These tests attempt to validate basic UI functionality. Tools such as the arithmetic GUI, smoothing GUI, etc. are not tested here. Hopefully these tests can serve as a template for those components.

Also, there is really no testing of the `specviz` UI at this point, although that can be added later.

Once this PR is accepted, it means that people merging subsequent PRs will actually need to pay attention to the CI testing status.

This closes #50 and also closes #53. It also now closes #162.

### CODE REVIEW

**Comment by drdavella** [comment]
I can't reproduce the travis test failures locally, so I'm going to need to spend some more time figuring out how to get things to pass.

Also, I'm getting a `glue` bug when using `numpy-1.14.0`, but I need to track down the exact cause.

**Comment by brechmos-stsci** [comment]
I grabbed the branch and am trying to run it.  I installed `qtbot` in my environment but am getting an error:
```
=============================================================== ERRORS =================================================================
___________________________________________ ERROR at setup of test_enter_valid_slice_text[0] ____________________________________________
file /Users/crjones/Documents/DATB/cubeviz/cubeviz/cubeviz/controls/tests/test_slice_controller.py, line 46
  @pytest.mark.parametrize('slice_index', [0, 100, 1000, 1024])
  def test_enter_valid_slice_text(qtbot, cubeviz_layout, slice_index):
file /Users/crjones/Documents/DATB/cubeviz/cubeviz/cubeviz/conftest.py, line 71
  @pytest.fixture(autouse=True)
  def reset_state(qtbot, cubeviz_layout):
E       fixture 'qtbot' not found
>       available fixtures: cache, capfd, capsys, cube_bounds, cubeviz_layout, doctest_namespace, monkeypatch, pytestconfig, record_xml_property, recwarn, reset_state, sync_params, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/crjones/Documents/DATB/cubeviz/cubeviz/cubeviz/conftest.py:71
__________________________________________ ERROR at setup of test_enter_valid_slice_text[100] ___________________________________________
file /Users/crjones/Documents/DATB/cubeviz/cubeviz/cubeviz/controls/tests/test_slice_controller.py, line 46
  @pytest.mark.parametrize('slice_index', [0, 100, 1000, 1024])
  def test_enter_valid_slice_text(qtbot, cubeviz_layout, slice_index):
file /Users/crjones/Documents/DATB/cubeviz/cubeviz/cubeviz/conftest.py, line 71
  @pytest.fixture(autouse=True)
  def reset_state(qtbot, cubeviz_layout):
E       fixture 'qtbot' not found
>       available fixtures: cache, capfd, capsys, cube_bounds, cubeviz_layout, doctest_namespace, monkeypatch, pytestconfig, record_xml_property, recwarn, reset_state, sync_params, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

Any idea why it might say "fixture qtbot" not found?  I tried going into python and doing an import on it and oddly am getting an error there too, but it does seem to be installed:
```
>>> import qtbot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/crjones/miniconda3/envs/cubeviz-dev/lib/python3.6/site-packages/qtbot.py", line 275
    print 'DONE'
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int 'DONE')?
>>>
```

**Comment by brechmos-stsci** [comment]
One other thing, "we" should write up a quick note on the wiki on how to run the tests and what packages need to be installed (i.e., qtbot).

**Comment by brechmos-stsci** [comment]
Ah, nm on the first problem. I had to install `pip install pytest-qt` instead and it is working.  

One interesting thing is it seems the text on the specviz plot actually looks reasonable in the cubeviz that popsup during the tests. What would be different about that environment than when we run the normal cubeviz from the command line. I like the look of the text in specviz when it pops up during the testing. :-)

**Comment by brechmos-stsci** [comment]
Nm on the wiki thing too, I wrote up a first pass. I created a `Developers` section on the main wiki page that has one entry so far to do with how to run tests:
image

**Comment by brechmos-stsci** [comment]
So, I reviewed the PR and it looks decent. It runs on my machine.

**Pull request merged**
