### PR TITLE
Move viewer options button to main glue toolbar

### PR DESCRIPTION
**Pull request by astrofrog**
screen shot 2017-11-20 at 16 55 16

### CODE REVIEW

**Comment by brechmos-stsci** [comment]
@astrofrog Is there a way to make the button the same style as the "Open Data" button?

**Comment by nmearl** [comment]
I think I lean more toward keeping the way the button is now. Reasoning being it's not a "tool" like the buttons that are part of the toolbar are. It's distinct with an action that's only applicable to the gui.

**Comment by astrofrog** [comment]
I agree with @nmearl, I deliberately made it look different. This is now rebased and ready to merge.

**Comment by drdavella** [comment]
Just rebased these changes on the latest `master`.

**Pull request merged**
