### PR TITLE
Fix compatibility with latest developer version of glue

### PR DESCRIPTION
**Pull request by astrofrog**
The combo fix is a quick fix - I'll try and do some refactoring of the combo boxes at some point to make the cubeviz code tidier and more robust.

Fixes https://github.com/spacetelescope/cubeviz/issues/410

### CODE REVIEW

**Comment by astrofrog** [comment]
Still needs a little work...

**Comment by astrofrog** [comment]
The AppVeyor build can be restarted once the glue conda packages for Windows are built (in a couple hours)

**Comment by astrofrog** [comment]
@drdavella @brechmos-stsci - this is ready to go!

**Comment by brechmos-stsci** [comment]
this appears to have re-introduced the 2D component over the 3D and will be fixed with #415

**Pull request merged**
